env:
  browser: true
  node: true
  es6: true
  jest: true
extends:
  - "plugin:react/recommended",
  - "eslint:recommended",
  - "plugin:security/recommended",
  - "plugin:jsx-a11y/recommended",
  - "plugin:cypress/recommended",
  - "plugin:prettier/recommended",
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - react-hooks
  - jest
  - import
  - security
  - jsx-a11y
  - cypress
rules:
  { "react-hooks/rules-of-hooks": error, "react-hooks/exhaustive-deps": warn, "no-console": ["error"] }
