trigger:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pre-agendamiento-front'

steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: ./Dockerfile
      containerRegistry: preagendamiento-cr